steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/adhyetrilpi/my-react-app", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/adhyetrilpi/my-react-app"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "container"
      - "clusters"
      - "get-credentials"
      - "react-cluster"
      - "--zone"
      - "us-central1-a"
      - "--project"
      - "adhyetrilpi"

  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "deployment.yaml"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=react-cluster"

images:
  - "gcr.io/adhyetrilpi/my-react-app"

options:
  logging: CLOUD_LOGGING_ONLY  # ✅ Fix for your error
