apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: gcr.io/adhyetrilpi/react-app:latest
          ports:
            - containerPort: 3000  # ✅ Matches EXPOSE 80 in Dockerfile
          readinessProbe:
            httpGet:
              path: /
              port: 3000  # ✅ Ensure it checks the correct port
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000 # ✅ Ensure container is healthy
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: LoadBalancer  # Exposes the app publicly
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3000     # External access
      targetPort: 3000  # ✅ Must match container port 80
