apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: gcr.io/adhyetrilpi/react-app:latest  # Uses your GCR image
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: LoadBalancer  # Exposes the app publicly
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
